#!/usr/bin/env python3

import os
import sys
import importlib.util

SNAKEBOX_ROOT = os.path.dirname(os.path.realpath(__file__))


__header__ = f"""
snakebox - Drop-in Python replacement for common shell utilities
Usage: snakebox <command> [args...]

To install snakebox, run:

  $ ./snakebox sb_install

Then add '{SNAKEBOX_ROOT}' to the beginning of your path
to run snakebox commands directly from your shell.
"""

__copyright__ = """
Copyright (c) 2022, Joshua Moore

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""


def run_utility(utility_name, args):
    # load utility module
    utility_spec = importlib.util.spec_from_file_location(
        f'{utility_name}',
        f'{SNAKEBOX_ROOT}/utilities/{utility_name}.py'
    )
    utility = importlib.util.module_from_spec(utility_spec)

    try:
        utility_spec.loader.exec_module(utility)
    except FileNotFoundError:
        print(f'No such snakebox utility: {utility_spec}')
        exit()
    
    # run utility
    return utility.main(args)


def list_utilities():
    ignore = ['__pycache__']
    result = []
    for util in os.listdir(SNAKEBOX_ROOT + '/utilities/'):
        if util in ignore:
            continue
        result.append(util.replace('.py', ''))
    return result


if __name__ == '__main__':
    # clean up invoked name
    invoked_name = sys.argv[0].replace('./', '')
    invoked_name = os.path.basename(
        os.path.normpath(invoked_name)
    )

    if invoked_name == 'snakebox':
        if len(sys.argv) < 2:
            print(__header__)
            print(__copyright__)
            exit()
        invoked_name = sys.argv[1]
        args = sys.argv[2:]
    else:
        args = sys.argv[1:]

    # handle special snakebox-internal commands
    if invoked_name == 'sb_install':
        args = [SNAKEBOX_ROOT] + list_utilities()
    elif invoked_name == 'sb_uninstall':
        args = [SNAKEBOX_ROOT] + list_utilities()
    elif invoked_name == 'sb_list':
        args = list_utilities()

    status_code = run_utility(invoked_name, args)

    # exit with status code returned by utility
    if status_code is None or not isinstance(status_code, int):
        raise ValueError(
            'snakebox utilities must return an integer status code, '\
            f'but {invoked_name} returned: {status_code}'
        )

    exit(status_code)
