#!/usr/bin/env python3

import os
import sys
import importlib.util

SNAKEBOX_ROOT = os.path.dirname(os.path.realpath(__file__))


def run_utility(utility_name, args):
    # load utility module
    utility_spec = importlib.util.spec_from_file_location(
        f'{utility_name}',
        f'{SNAKEBOX_ROOT}/utilities/{utility_name}.py'
    )
    utility = importlib.util.module_from_spec(utility_spec)

    try:
        utility_spec.loader.exec_module(utility)
    except FileNotFoundError:
        print(f'No such snakebox utility: {utility_spec}')
        exit()
    
    # run utility
    return utility.main(args)


def list_utilities():
    ignore = ['__pycache__']
    result = []
    for util in os.listdir(SNAKEBOX_ROOT + '/utilities/'):
        if util in ignore:
            continue
        result.append(util.replace('.py', ''))
    return result


if __name__ == '__main__':
    # clean up invoked name
    invoked_name = sys.argv[0].replace('./', '')
    invoked_name = os.path.basename(
        os.path.normpath(invoked_name)
    )

    if invoked_name == 'snakebox':
        if len(sys.argv) < 2:
            print("snakebox")
            print("Usage: snakebox <command> [args...]")
            print("""

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
            """)
            exit()
        invoked_name = sys.argv[1]
        args = sys.argv[2:]
    else:
        args = sys.argv[1:]

    # handle special snakebox-internal commands
    if invoked_name == 'sb_install':
        args = [SNAKEBOX_ROOT] + list_utilities()
    elif invoked_name == 'sb_uninstall':
        args = [SNAKEBOX_ROOT] + list_utilities()
    elif invoked_name == 'sb_list':
        args = list_utilities()

    result = run_utility(invoked_name, args)

    # exit with a failing status code if the utility returned one
    if result:
        exit(result)
